# Site settings
title: Steffen Adventures
header-img: img/IMG_1719.jpg
email: ""
description: "The international wanderings of Robynn and Michael"
baseurl: "/steffen-adventures"
url: ""

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
